[package]
name = "loadngo_eab"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A hyper-dimensional player profile, entitlement, and achievement blockchain of the player journey"

[dependencies]
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
sha2.workspace = true
blake3.workspace = true
chrono.workspace = true
hex.workspace = true
actix-web.workspace = true
clap.workspace = true
uuid.workspace = true
once_cell.workspace = true
sled.workspace = true
fs2.workspace = true
qcoin-consensus.workspace = true
qcoin-ledger.workspace = true
qcoin-script.workspace = true
qcoin-types.workspace = true
loadngo-proactor.workspace = true
loadngo-network.workspace = true
ureq.workspace = true
anyhow.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
