[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
blake3 = "1"
chrono = "0.4"
hex = "0.4"
actix-web = "4"
clap = { version = "4", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }
once_cell = "1"
sled = "0.34"
fs2 = "0.4"
qcoin-consensus = { path = "../../qcoin/qcoin-consensus" }
qcoin-ledger = { path = "../../qcoin/qcoin-ledger" }
qcoin-script = { path = "../../qcoin/qcoin-script" }
qcoin-types = { path = "../../qcoin/qcoin-types" }
